fep:
  simulator:
    diagnostics-base-url: http://127.0.0.1:18082

spring:
  flyway:
    locations: classpath:db/migration,classpath:db/seed
  jpa:
    properties:
      hibernate:
        show_sql: false
