spring:
  flyway:
    locations: classpath:db/migration,classpath:db/seed
  jpa:
    properties:
      hibernate:
        show_sql: false
  session:
    store-type: none

order:
  session:
    expiry-reconciliation:
      enabled: false
    recovery:
      enabled: false