springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

server:
  servlet:
    session:
      cookie:
        same-site: none
        secure: true

auth:
  totp:
    secret-store: vault
