CREATE TABLE IF NOT EXISTS accounts (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  account_no VARCHAR(64) NOT NULL UNIQUE,
  member_no VARCHAR(64) NOT NULL,
  currency VARCHAR(16) NOT NULL,
  cash_balance DECIMAL(19, 4) NOT NULL,
  daily_sell_limit DECIMAL(19, 4) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  version BIGINT
);

CREATE TABLE IF NOT EXISTS orders (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  account_id BIGINT NOT NULL,
  cl_ord_id VARCHAR(64) NOT NULL UNIQUE,
  symbol VARCHAR(32) NOT NULL,
  side VARCHAR(8) NOT NULL,
  order_qty DECIMAL(19, 4) NOT NULL,
  order_price DECIMAL(19, 4) NOT NULL,
  status VARCHAR(32) NOT NULL,
  requested_at TIMESTAMP NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  version BIGINT
);

CREATE TABLE IF NOT EXISTS positions (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  account_id BIGINT NOT NULL,
  symbol VARCHAR(32) NOT NULL,
  qty DECIMAL(19, 4) NOT NULL,
  avg_price DECIMAL(19, 4) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  version BIGINT,
  CONSTRAINT uk_positions_account_symbol UNIQUE (account_id, symbol)
);

CREATE TABLE IF NOT EXISTS executions (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  order_id BIGINT NOT NULL,
  account_id BIGINT NOT NULL,
  cl_ord_id VARCHAR(64) NOT NULL,
  symbol VARCHAR(32) NOT NULL,
  side VARCHAR(8) NOT NULL,
  exec_qty DECIMAL(19, 4) NOT NULL,
  exec_price DECIMAL(19, 4) NOT NULL,
  executed_at TIMESTAMP NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  version BIGINT
);

CREATE TABLE IF NOT EXISTS journal_entries (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  order_id BIGINT NOT NULL,
  entry_type VARCHAR(32) NOT NULL,
  amount DECIMAL(19, 4) NOT NULL,
  memo VARCHAR(255),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  version BIGINT
);

CREATE TABLE IF NOT EXISTS ledger_entries (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  journal_entry_id BIGINT NOT NULL,
  account_id BIGINT NOT NULL,
  ledger_type VARCHAR(32) NOT NULL,
  direction VARCHAR(16) NOT NULL,
  amount DECIMAL(19, 4) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  version BIGINT
);

CREATE TABLE IF NOT EXISTS ledger_entry_refs (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  ledger_entry_id BIGINT NOT NULL,
  ref_type VARCHAR(32) NOT NULL,
  ref_value VARCHAR(128) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  version BIGINT
);

CREATE INDEX IF NOT EXISTS idx_orders_account_id ON orders(account_id);
CREATE INDEX IF NOT EXISTS idx_orders_cl_ord_id ON orders(cl_ord_id);
CREATE INDEX IF NOT EXISTS idx_positions_account_symbol ON positions(account_id, symbol);
CREATE INDEX IF NOT EXISTS idx_executions_account_symbol ON executions(account_id, symbol);
