package com.fix.channel.entity;

public enum AuditAction {
  AUTH_REGISTER,
  AUTH_LOGIN_FAILURE,
  AUTH_LOGIN_SUCCESS,
  AUTH_TOTP_ENROLLMENT_BOOTSTRAP,
  AUTH_TOTP_ENROLLMENT_CONFIRMED,
  AUTH_MFA_RECOVERY_PROOF_ISSUED,
  AUTH_TOTP_REBIND_INITIATED,
  AUTH_TOTP_REBIND_CONFIRMED,
  AUTH_TOTP_REBIND_FAILED,
  AUTH_TOTP_SECRET_TERMINALIZED,
  PASSWORD_RECOVERY_FORGOT,
  PASSWORD_RECOVERY_CHALLENGE_ISSUED,
  PASSWORD_RECOVERY_RESET,
  LOGOUT,
  MEMBER_PROFILE_UPDATE,
  MEMBER_PASSWORD_UPDATE,
  ORDER_SESSION_CREATE,
  ORDER_SESSION_EXTENDED,
  ORDER_SESSION_OTP_VERIFIED,
  ORDER_SESSION_OTP_RATE_LIMITED,
  ORDER_SESSION_OTP_REPLAYED,
  ORDER_SESSION_EXECUTED,
  ORDER_SESSION_ESCALATED,
  ORDER_SESSION_FAILED,
  ORDER_SESSION_EXPIRED;

  public String value() {
    return name();
  }
}
