CREATE TABLE IF NOT EXISTS order_session (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  order_ref VARCHAR(64) NOT NULL,
  status VARCHAR(32) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
